name: project deploy

on:
  push:
    branches: [prod, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: install dependencies
        run: npm ci
      - name: run test
        id: checkTest
        run: npm test
        continue-on-error: true
      - name: check fail
        if: steps.checkTest.outcome != 'success'
        run: |
          echo email: $(EMAIL_ADDRESS)
          npm run email
          exit 1
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env variables
        run: |
          echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
      - name: deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSHKEY }}
          script: |
            cd /var/www/testnode.com/${{ env.BRANCH_NAME }}/current/
            pm2 deploy ecosystem.config.js ${{ env.BRANCH_NAME }} update
